[build]
  publish = "dist"
  command = "npm run build"

[functions]
  # Include the ai directory in the functions bundle
  included_files = ["ai/**/*"]

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
